namespace GorillaInfoWatch.Models.Enumerations
{
    public enum Symbols : byte
    {
        None,

        // People
        Dev,
        Gizmo,
        Cresmondo,
        BloodJman,
        H4RNS,
        Astrid,
        Deactivated,
        Cyan,
        Chucken,
        Socks,
        Maple,
        Lapis,
        Kronicahl,

        // Icons
        Verified,
        Info,
        Patreon,
        KoFi,
        OpenSpeaker,
        MutedSpeaker,
        ForceMuteSpeaker,
        ModStick,
        FingerPainter,
        Illustrator,
        ForestGuideStick,
        InfoWatch,
        AACreator,
        TemplateHead,
        TemplateFace,
        Ignore,
        Image,
        Bell,
        BellRing,
        RedFlag,
        GreenFlag,
        Croptop,
        Rainbow,
        LightBulb,
        Camera,
        Vibration,
        Gun,
        Invisibility,
        Particles,
        Phone,
        Play,
        Stop,
        ExternalLink,
        Minus,
        Plus,
    }
}